export {HomePage} from './HomePage/homePage.screen'
export {LogoutScreen} from './LogoutScreen/logoutScreen.screen'
export {LoginScreen} from './LoginScreen/loginScreen.screen'
export {RegisterScreen} from './RegisterScreen/registerScreen.screen';
export {DashboardScreen} from './DashboardScreen/dashboardScreen.screen'
export {ProfileScreen} from './ProfileScreen/profileScreen.screen'
export {SearchPeopleScreen} from './SearchPeopleScreen/searchPeople.screen'
export {MyFriendsScreen} from './MyFriendsScreen/myFriendsScreen.component'
export {EditarPerfilScreen} from './EditarPerfilScreen/editarPerfilScreen.component'