name: Hello world integração continua
on: 
  push: 
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  OlaMundo:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: Diga
        run: echo Hello-World!
